project:
  type: website

website:
  title: "Yu-En Hsu"
  google-analytics: "G-FRQ30Q4RJP"
  description: "Hey! I am Yu-En."
  favicon: assets/pelican.png
  draft-mode: visible
  site-url: "https://yuenhsu.com/"
  repo-url: https://github.com/yuenhsu/yuenhsu.github.io
  navbar:
    logo: assets/pelican.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - posts.qmd
  page-footer: 
    border: true
    center: Â© 2019-2025, Yu-En Hsu
    right: |
      <a  href="https://icons8.com/icon/iibADLuA7AH6/pelican">Pelican</a> icon by <a href="https://icons8.com">Icons8</a>
  comments: 
    giscus: 
      repo: yuenhsu/yuenhsu.github.io
      repo-id: R_kgDOPZcehw
      category: General
      category-id: DIC_kwDOPZceh84Cuzgu
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      theme: preferred_color_scheme
      language: en

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - assets/theme1.scss
    toc: true
    css: assets/styles.css
    highlight-style: "github-dark"
    link-external-newwindow: true
    link-external-filter: "(yuenhsu|yhsu10)"
    link-external-icon: true